[package]
name = "waline-db"
version.workspace = true
edition.workspace = true

[features]
default = ["postgres", "mysql", "sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]

[dependencies]
waline-common = { workspace = true, features = ["sqlx"] }
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait = "0.1"
