[package]
name = "waline-auth"
version.workspace = true
edition.workspace = true

[dependencies]
waline-common.workspace = true
jsonwebtoken.workspace = true
bcrypt.workspace = true
totp-rs.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
md5 = "0.7"
base64.workspace = true
rand = "0.8"
